
name: Run tests and upload coverage

on:
  push:
    branches:
      - main  # Defina os branches de sua preferência

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npx jest --coverage

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          # Remova o token, pois o repositório é público
          slug: joaovictor-ip4y/TesteB

      - name: Wait for Codecov to process
        run: |
          # Aguarda o Codecov processar a cobertura
          sleep 60  # Tempo de espera para garantir que os dados sejam processados

      - name: Ensure coverage is above 60%
        run: |
          # Obtém os dados de cobertura da API do Codecov
          response=$(curl -s https://codecov.io/api/gh/${{ github.repository }}/reports/coverage)
          echo "Response from Codecov API: $response"
          
          # Verifica se a resposta está vazia ou nula
          if [[ -z "$response" || "$response" == "null" ]]; then
              echo "Failed to retrieve valid coverage data from Codecov API."
              exit 1
          fi
          
          # Extrai a cobertura total da resposta
          coverage=$(echo "$response" | jq -r '.total.coverage // 0')
          
          # Verifica se a cobertura é inferior a 60%
          if (( $(echo "$coverage < 60" | bc -l) )); then
              echo "Coverage is below 60% ($coverage%), failing the workflow."
              exit 1
          fi
          
          echo "Coverage is above 60% ($coverage%), proceeding."
        shell: /bin/bash -e {0}
