name: Test and Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: |
          composer install

      - name: Run tests
        run: |
          vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: coverage.xml

      - name: Wait for Codecov to process
        run: |
          # Aumenta o tempo de espera para garantir que o Codecov processe a cobertura
          sleep 60

      - name: Ensure coverage is above 60%
        run: |
          # Obtém os dados de cobertura da API do Codecov
          response=$(curl -s https://codecov.io/api/gh/${{ github.repository }}/reports/coverage)
          echo "Response from Codecov API: $response"
          
          # Valida se a resposta está vazia ou nula
          if [[ -z "$response" || "$response" == "null" ]]; then
              echo "Failed to retrieve valid coverage data from Codecov API."
              exit 1
          fi
          
          # Extrai a cobertura total da resposta
          coverage=$(echo "$response" | jq -r '.total.coverage // 0')
          
          # Verifica se a cobertura é inferior a 60%
          if (( $(echo "$coverage < 60" | bc -l) )); then
              echo "Coverage is below 60% ($coverage%), failing the workflow."
              exit 1
          fi
          
          echo "Coverage is above 60% ($coverage%), proceeding."
        shell: /bin/bash -e {0}
