name: PHP Code Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  phpunit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: |
          composer install

      - name: Run PHPUnit tests with coverage
        run: |
          vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

      - name: Check code coverage
        run: |
          COVERAGE=$(php -r "libxml_use_internal_errors(true); \$xml = simplexml_load_file('coverage.xml'); echo \$xml->project->metrics->coverage;")
          if (( $(echo "$COVERAGE < 60" | bc -l) )); then
            echo "Code coverage is below 60%, coverage: $COVERAGE"
            exit 1
          fi
