name: Coverage Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuração do PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Altere conforme a versão do PHP usada no seu projeto

      # Instalar dependências do projeto
      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      # Executar os testes com cobertura
      - name: Run tests with coverage
        run: |
          vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml
        env:
          XDEBUG_MODE: coverage

      # Analisar a cobertura mínima
      - name: Check code coverage
        run: |
          COVERAGE=$(php -r "echo (int) preg_replace('/[^0-9]/', '', shell_exec('grep "Lines" coverage.xml | grep -oP \'[0-9]+(?=%)\''));")
          echo "Code coverage: $COVERAGE%"
          if [ "$COVERAGE" -lt 60 ]; then
            echo "Code coverage is below 60%. Failing the workflow."
            exit 1
          fi
